#!/usr/bin/env python3
"""Generate xbox/compat/lus_cvars.h from SoH's cvar .cmake files.

SoH injects the CVAR_* names as -D compile definitions from CMake. We reproduce that
as a force-included header so the Xbox libultraship/soh build uses identical cvar keys.
Processing order matches soh/CMakeLists.txt: soh-cvars.cmake, then lus-cvars.cmake
(which include()s libultraship/cmake/cvars.cmake at its end). CMake cache semantics:
`set(X v CACHE ...)` sets only if X is unset (first wins); plain `set(X v)` always sets.
"""
import re, os

ROOT = r'D:/Git/Shipwright'
FILES = [
    'CMake/soh-cvars.cmake',
    'CMake/lus-cvars.cmake',
    'libultraship/cmake/cvars.cmake',
]
set_re = re.compile(r'set\(\s*([A-Za-z0-9_]+)\s+"([^"]*)"\s*(CACHE\b[^)]*)?\)')

vals = {}

def process(path, seen_files):
    ap = os.path.join(ROOT, path)
    if not os.path.exists(ap):
        return
    for line in open(ap, encoding='utf-8'):
        s = line.strip()
        inc = re.match(r'include\(\s*"?([^)"]+)"?\s*\)', s)
        if inc:
            process(inc.group(1), seen_files)
            continue
        m = set_re.search(s)
        if not m:
            continue
        name, value, cache = m.group(1), m.group(2), m.group(3)
        if cache and name in vals:
            continue  # cache var already set -> first wins
        vals[name] = value

for f in FILES:
    process(f, set())

# Resolve ${VAR} references iteratively.
ref_re = re.compile(r'\$\{([A-Za-z0-9_]+)\}')
for _ in range(10):
    changed = False
    for k, v in list(vals.items()):
        def repl(m):
            return vals.get(m.group(1), m.group(0))
        nv = ref_re.sub(repl, v)
        if nv != v:
            vals[k] = nv
            changed = True
    if not changed:
        break

cvars = {k: v for k, v in vals.items() if k.startswith('CVAR_')}
unresolved = [k for k, v in cvars.items() if '${' in v]

out = os.path.join(ROOT, 'xbox/compat/lus_cvars.h')
with open(out, 'w', encoding='utf-8') as fh:
    fh.write('// AUTO-GENERATED by xbox/compat/gen_cvars.py from SoH\'s cvar .cmake files.\n')
    fh.write('// Reproduces the -DCVAR_* compile definitions CMake injects, as a force-include.\n')
    fh.write('#pragma once\n\n')
    for k in sorted(cvars):
        fh.write('#ifndef %s\n#define %s "%s"\n#endif\n' % (k, k, cvars[k]))

print('wrote %s with %d CVAR_ macros' % (out, len(cvars)))
if unresolved:
    print('WARNING unresolved:', unresolved)
