// AUTO-GENERATED by xbox/compat/gen_cvars.py from SoH's cvar .cmake files.
// Reproduces the -DCVAR_* compile definitions CMake injects, as a force-include.
#pragma once

#ifndef CVAR_ALLOW_BACKGROUND_INPUTS
#define CVAR_ALLOW_BACKGROUND_INPUTS "gAllowBackgroundInputs"
#endif
#ifndef CVAR_AUDIO_CHANNELS_SETTING
#define CVAR_AUDIO_CHANNELS_SETTING "gAudioChannelsSetting"
#endif
#ifndef CVAR_CONSOLE_WINDOW_OPEN
#define CVAR_CONSOLE_WINDOW_OPEN "gOpenWindows.Console"
#endif
#ifndef CVAR_CONTROLLER_CONFIGURATION_WINDOW_OPEN
#define CVAR_CONTROLLER_CONFIGURATION_WINDOW_OPEN "gControllerConfigurationEnabled"
#endif
#ifndef CVAR_CONTROLLER_DISCONNECTED_WINDOW_OPEN
#define CVAR_CONTROLLER_DISCONNECTED_WINDOW_OPEN "gOpenWindows.ControllerDisconnected"
#endif
#ifndef CVAR_CONTROLLER_REORDERING_WINDOW_OPEN
#define CVAR_CONTROLLER_REORDERING_WINDOW_OPEN "gOpenWindows.ControllerReordering"
#endif
#ifndef CVAR_ENABLE_MULTI_VIEWPORTS
#define CVAR_ENABLE_MULTI_VIEWPORTS "gSettings.EnableMultiViewports"
#endif
#ifndef CVAR_GAME_OVERLAY_FONT
#define CVAR_GAME_OVERLAY_FONT "gSettings.OverlayFont"
#endif
#ifndef CVAR_GFX_DEBUGGER_WINDOW_OPEN
#define CVAR_GFX_DEBUGGER_WINDOW_OPEN "gOpenWindows.GfxDebugger"
#endif
#ifndef CVAR_IMGUI_CONTROLLER_NAV
#define CVAR_IMGUI_CONTROLLER_NAV "gSettings.ControlNav"
#endif
#ifndef CVAR_INTERNAL_RESOLUTION
#define CVAR_INTERNAL_RESOLUTION "gSettings.InternalResolution"
#endif
#ifndef CVAR_LOW_RES_MODE
#define CVAR_LOW_RES_MODE "gSettings.LowResMode"
#endif
#ifndef CVAR_MENU_BAR_OPEN
#define CVAR_MENU_BAR_OPEN "gSettings.OpenMenuBar"
#endif
#ifndef CVAR_MSAA_VALUE
#define CVAR_MSAA_VALUE "gSettings.MSAAValue"
#endif
#ifndef CVAR_PREFIX_ADVANCED_RESOLUTION
#define CVAR_PREFIX_ADVANCED_RESOLUTION "gSettings.AdvancedResolution"
#endif
#ifndef CVAR_PREFIX_AUDIO
#define CVAR_PREFIX_AUDIO "gAudioEditor"
#endif
#ifndef CVAR_PREFIX_CHEAT
#define CVAR_PREFIX_CHEAT "gCheats"
#endif
#ifndef CVAR_PREFIX_CONTROLLERS
#define CVAR_PREFIX_CONTROLLERS "gSettings.Controllers"
#endif
#ifndef CVAR_PREFIX_COSMETIC
#define CVAR_PREFIX_COSMETIC "gCosmetics"
#endif
#ifndef CVAR_PREFIX_DEVELOPER_TOOLS
#define CVAR_PREFIX_DEVELOPER_TOOLS "gDeveloperTools"
#endif
#ifndef CVAR_PREFIX_ENHANCEMENT
#define CVAR_PREFIX_ENHANCEMENT "gEnhancements"
#endif
#ifndef CVAR_PREFIX_GAMEPLAY_STATS
#define CVAR_PREFIX_GAMEPLAY_STATS "gGameplayStats"
#endif
#ifndef CVAR_PREFIX_GENERAL
#define CVAR_PREFIX_GENERAL "gGeneral"
#endif
#ifndef CVAR_PREFIX_RANDOMIZER_ENHANCEMENT
#define CVAR_PREFIX_RANDOMIZER_ENHANCEMENT "gRandoEnhancements"
#endif
#ifndef CVAR_PREFIX_RANDOMIZER_SETTING
#define CVAR_PREFIX_RANDOMIZER_SETTING "gRandoSettings"
#endif
#ifndef CVAR_PREFIX_REMOTE
#define CVAR_PREFIX_REMOTE "gRemote"
#endif
#ifndef CVAR_PREFIX_SETTING
#define CVAR_PREFIX_SETTING "gSettings"
#endif
#ifndef CVAR_PREFIX_TIME_DISPLAY
#define CVAR_PREFIX_TIME_DISPLAY "gTimeDisplay"
#endif
#ifndef CVAR_PREFIX_TRACKER
#define CVAR_PREFIX_TRACKER "gTrackers"
#endif
#ifndef CVAR_PREFIX_WINDOW
#define CVAR_PREFIX_WINDOW "gOpenWindows"
#endif
#ifndef CVAR_SCRIPT_SAFE_LEVEL
#define CVAR_SCRIPT_SAFE_LEVEL "gScriptSafeLevel"
#endif
#ifndef CVAR_SDL_WINDOWED_FULLSCREEN
#define CVAR_SDL_WINDOWED_FULLSCREEN "gSettings.SdlWindowedFullscreen"
#endif
#ifndef CVAR_SIMULATED_INPUT_LAG
#define CVAR_SIMULATED_INPUT_LAG "gSettings.SimulatedInputLag"
#endif
#ifndef CVAR_STATS_WINDOW_OPEN
#define CVAR_STATS_WINDOW_OPEN "gOpenWindows.Stats"
#endif
#ifndef CVAR_TEXTURE_FILTER
#define CVAR_TEXTURE_FILTER "gSettings.TextureFilter"
#endif
#ifndef CVAR_VSYNC_ENABLED
#define CVAR_VSYNC_ENABLED "gSettings.VsyncEnabled"
#endif
#ifndef CVAR_Z_FIGHTING_MODE
#define CVAR_Z_FIGHTING_MODE "gSettings.ZFightingMode"
#endif
